apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: consul
  name: consul-public
  namespace: default
spec:
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  publishNotReadyAddresses: true
  selector:
    app: consul
    component: server
    release: consul
  sessionAffinity: None
  type: NodePort
