apiVersion: apps/v1
kind: Deployment
metadata:
  name: award-consul
  annotations:
    mesh.megaease.com/service-name: "award-consul"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: award-consul
  template:
    metadata:
      labels:
        app: award-consul
    spec:
      containers:
        - image:  megaease/easemesh-demo-award:jdk-slim-4
          name: award-consul
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          command: ["/bin/sh"]
          args: ["-c", "java -server -jar  -Dspring.profiles.active=sit  meshdemo-0.0.1-SNAPSHOT.jar"]
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /poc/application-sit.yml
              name: configmap-volume-0
              subPath: application-sit.yml
          ports:
            - containerPort: 80
          env:
          - name: ZIPKIN_SERVER_URL
            value: http://192.168.0.200:32176/api/v2/spans
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-sit-yml
                path: application-sit.yml
            name: award-consul
          name: configmap-volume-0
      restartPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: award-consul
data:
  application-sit-yml: |
    server:
      port: 80
    spring:
      application:
        name: award-consul
      cloud:
        consul:
          host: localhost
          port: 13009
    easemesh:
      demo:
        remote-service: delivery-consul
