apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consul
  labels:
    app: order-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-consul
  template:
    metadata:
      labels:
        app: order-consul
    spec:
      containers:
      - name: order-consul
        image: megaease/consuldemo:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: order-consul
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONSUL_ADDRESS
          value: consul-server-0.consul-server.default:8500
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_PORT
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: order-consul
spec:
  selector:
    app: order-consul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: order-consul-public
spec:
  type: NodePort
  selector:
    app: order-consul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
