apiPort: 13009
externalServiceRegistry: consul-service-registry
heartbeatInterval: 5s
ingressPort: 19527
kind: MeshController
name: easemesh-controller
registryType: consul
security: null


# TODO
cleanExternalService: true