apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mesh-service
  name: restaurant-mesh-beijing-android
  annotations:
    mesh.megaease.com/service-name: restaurant-mesh
    mesh.megaease.com/service-labels: release=restaurant-mesh-beijing-android
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mesh-beijing-android
  template:
    metadata:
      labels:
        app: restaurant-mesh-beijing-android
    spec:
      containers:
        - image: megaease/easemesh-demo-restaurant:latest
          name: restaurant-mesh-beijing-android
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          command: ["/bin/sh"]
          args: ["-c", "java -server -jar  -Dspring.profiles.active=sit  meshdemo-0.0.1-SNAPSHOT.jar"]
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 1Gi
          volumeMounts:
            - mountPath: /poc/application-sit.yml
              name: configmap-volume-0
              subPath: application-sit.yml
          ports:
            - containerPort: 80
          env:
          - name: SERVICE_NAME
            value: restaurant-mesh-beijing-android
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-sit-yml
                path: application-sit.yml
            name: restaurant-mesh
          name: configmap-volume-0
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-mesh-beijing-android
  namespace: mesh-service
spec:
  selector:
    app: restaurant-mesh-beijing-android
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
