apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mesh.megaease.com/service-name: delivery
  name: delivery
  namespace: mesh-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: megaease/consuldemo:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: delivery

---

apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: mesh-service
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
