apiVersion: mesh.megaease.com/v1alpha1
kind: ServiceCanary
metadata:
  name: delivery-mesh-canary
spec:
  selector:
    matchServices: [delivery-mesh]
    matchInstanceLabels: {release: delivery-mesh-canary}
  trafficRules:
    headers:
      X-Location:
        exact: Beijing

requestAdaptor:
  header:
    set: X-EaseMesh-ServiceCanary: delivery-mesh-canary
  filter:
    matchAllHeaders: true
    header:
      X-EaseMesh-ServiceCanary:
        empty: true
      X-Location:
        exact: Beijing

candidates:
  filter:
    matchAllHeaders: true
    headers:
      X-EaseMesh-ServiceCanary:
        exact: delivery-mesh-canary
      X-Location:
        exact: Beijing