apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mesh.megaease.com/service-name: delivery-mesh
  name: delivery-mesh
  namespace: mesh-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-mesh
  template:
    metadata:
      labels:
        app: delivery-mesh
    spec:
      containers:
      - name: delivery-mesh
        image: megaease/consuldemo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: delivery-mesh
        - name: ZIPKIN_SERVER_URL
          value: https://dev.megaease.cn/zipkin

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: delivery-mesh
#  namespace: mesh-service
#spec:
#  selector:
#    app: delivery-mesh
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
