apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mesh.megaease.com/service-name: restaurant-mesh
  name: restaurant-mesh
  namespace: mesh-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mesh
  template:
    metadata:
      labels:
        app: restaurant-mesh
    spec:
      containers:
      - name: restaurant-mesh
        image: megaease/consuldemo:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: restaurant-mesh
        - name: ZIPKIN_SERVER_URL
          value: http://192.168.0.200:32176/api/v2/spans

---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-mesh
  namespace: mesh-service
spec:
  selector:
    app: restaurant-mesh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
