apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mesh.megaease.com/service-name: order-mesh
  name: order-mesh
  namespace: mesh-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mesh
  template:
    metadata:
      labels:
        app: order-mesh
    spec:
      containers:
      - name: order-mesh
        image: megaease/consuldemo:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: order-mesh
        - name: ZIPKIN_SERVER_URL
          value: https://dev.megaease.cn/zipkin

---

apiVersion: v1
kind: Service
metadata:
  name: order-mesh
  namespace: mesh-service
spec:
  selector:
    app: order-mesh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: order-mesh-public
  namespace: mesh-service
spec:
  type: NodePort
  selector:
    app: order-mesh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
