apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mesh.megaease.com/service-name: order
  name: order
  namespace: mesh-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: megaease/consuldemo:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: order

---

apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: mesh-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: order-public
  namespace: mesh-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
